"""Add mini_tutorial field to Module

Revision ID: c52f83784ffb
Revises: 18521b5b4502
Create Date: 2025-12-12 00:54:09.298920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52f83784ffb'
down_revision = '18521b5b4502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mini_tutorial', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('mini_tutorial')

    # ### end Alembic commands ###
